'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CodeLadder.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;GameML xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        '''  xsi:noNamespaceSchemaLocation=&quot;GameML.xsd&quot;
        '''  version=&quot;1&quot;&gt;
        '''  &lt;game name=&quot;CodeLadder&quot;&gt;
        '''    &lt;language&gt;CSharp&lt;/language&gt;
        '''    &lt;start&gt;1&lt;/start&gt;
        '''  &lt;/game&gt;
        '''
        '''   &lt;!--
        '''   CSharp Level 1
        '''   --&gt;
        '''  &lt;puzzle&gt;
        '''    &lt;description&gt;Fix the variable declaration in this broken function.&lt;/description&gt;
        '''    &lt;code entryPoint=&quot;Main&quot;&gt;
        '''      static int Main()
        '''      {
        '''        int p1 = 3,
        '''        return p1;
        '''      }
        '''      &lt;/code&gt;
        '''    &lt;results&gt;
        '''      &lt;expec [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CSharp() As String
            Get
                Return ResourceManager.GetString("CSharp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot;&gt;
        '''  &lt;xs:element name=&quot;GameML&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:sequence&gt;
        '''        &lt;xs:element ref=&quot;game&quot;/&gt;
        '''        &lt;xs:element maxOccurs=&quot;unbounded&quot; ref=&quot;puzzle&quot;/&gt;
        '''      &lt;/xs:sequence&gt;
        '''      &lt;xs:attribute name=&quot;version&quot; use=&quot;required&quot; type=&quot;xs:integer&quot;/&gt;
        '''    &lt;/xs:complexType&gt;
        '''  &lt;/xs:element&gt;
        '''  &lt;xs:element name=&quot;game&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:sequence&gt;
        '''        &lt;xs:element ref=&quot;lang [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GameML() As String
            Get
                Return ResourceManager.GetString("GameML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;GameML xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        '''  xsi:noNamespaceSchemaLocation=&quot;GameML.xsd&quot;
        '''  version=&quot;1&quot;&gt;
        '''  &lt;game name=&quot;CodeLadder&quot;&gt;
        '''    &lt;language&gt;VisualBasic&lt;/language&gt;
        '''    &lt;level&gt;1&lt;/level&gt;   
        '''    &lt;start&gt;1&lt;/start&gt;   
        '''  &lt;/game&gt;
        '''
        '''   &lt;!--
        '''   VB Chapter 1
        '''   --&gt;
        '''  &lt;puzzle level=&quot;1&quot;&gt;
        '''    &lt;description&gt;Fix the variable declaration in this broken function.&lt;/description&gt;
        '''    &lt;code&gt;
        '''      Public Function Puzzle() As Integer
        '''        Dim *intStrange As Integer = 3
        '''        Return *intS [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property VisualBasic() As String
            Get
                Return ResourceManager.GetString("VisualBasic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE GameML [
        '''  &lt;!ENTITY commonControls &apos;
        '''        Private frm As New Form With {.Name = &quot;frm&quot;, .Text = &quot;Hello!&quot;, .AutoSize = True}
        '''  
        '''        Private lblPrompt As New Label With {.Name = &quot;lblPrompt&quot;, .Location = New System.Drawing.Point(25, 10), .AutoSize = True}
        '''        Private WithEvents btnClose As New Button With {.Name = &quot;btnClose&quot;, .Text = &quot;Close&quot;, .AutoSize = True, 
        '''                                                        .Location = New System.Drawing.Point(75, 75)}
        '''        Private Sub Cl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Week1VisualBasic() As String
            Get
                Return ResourceManager.GetString("Week1VisualBasic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE GameML [
        '''  &lt;!ENTITY commonControls &apos;
        '''        Private frm As New Form With {.Name = &quot;frm&quot;, .Text = &quot;Hello!&quot;, .AutoSize = True}
        '''  
        '''        Private lblPrompt As New Label With {.Name = &quot;lblPrompt&quot;, .Location = New System.Drawing.Point(25, 10), .AutoSize = True}
        '''        Private WithEvents btnClose As New Button With {.Name = &quot;btnClose&quot;, .Text = &quot;Close&quot;, .AutoSize = True, 
        '''                                                        .Location = New System.Drawing.Point(75, 225)}
        '''        Private Sub C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Week2VisualBasic() As String
            Get
                Return ResourceManager.GetString("Week2VisualBasic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;GameML xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        '''  xsi:noNamespaceSchemaLocation=&quot;GameML.xsd&quot;
        '''  version=&quot;1&quot;&gt;
        '''  &lt;game name=&quot;CodeLadder&quot;&gt;
        '''    &lt;language&gt;VisualBasic&lt;/language&gt;
        '''    &lt;level&gt;3&lt;/level&gt;   
        '''    &lt;start&gt;1&lt;/start&gt;   
        '''  &lt;/game&gt;
        '''
        '''  
        '''  
        '''  &lt;puzzle&gt;
        '''    &lt;description&gt;
        '''      Fix the variable declaration.
        '''    &lt;/description&gt;
        '''    &lt;help&gt;https://code.google.com/p/code-ladder/wiki/Variable#Variable_Naming_Rules&lt;/help&gt;
        '''    &lt;code&gt;
        '''      &lt;header&gt;
        '''        Public Function Puzzle() As Integ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Week3VisualBasic() As String
            Get
                Return ResourceManager.GetString("Week3VisualBasic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;GameML xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        '''  xsi:noNamespaceSchemaLocation=&quot;GameML.xsd&quot;
        '''  version=&quot;1&quot;&gt;
        '''  &lt;game name=&quot;CodeLadder&quot;&gt;
        '''    &lt;language&gt;VisualBasic&lt;/language&gt;
        '''    &lt;level&gt;4&lt;/level&gt;   
        '''    &lt;start&gt;1&lt;/start&gt;   
        '''  &lt;/game&gt;
        '''
        '''  &lt;!--
        '''   VB Chapter 4
        '''   --&gt;
        '''  &lt;puzzle&gt;
        '''    &lt;description&gt;Create a function that returns &quot;It&apos;s cold&quot; if intTemp is less than 40
        '''    &lt;/description&gt;
        '''    &lt;code entryPoint=&quot;Example&quot;&gt;
        '''      Public Function Example (ByVal intTemp As Integer) As String
        '''    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Week4VisualBasic() As String
            Get
                Return ResourceManager.GetString("Week4VisualBasic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;GameML xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        '''  xsi:noNamespaceSchemaLocation=&quot;GameML.xsd&quot;
        '''  version=&quot;1&quot;&gt;
        '''  &lt;game name=&quot;CodeLadder&quot;&gt;
        '''    &lt;language&gt;VisualBasic&lt;/language&gt;
        '''    &lt;level&gt;5&lt;/level&gt;   
        '''    &lt;start&gt;1&lt;/start&gt;   
        '''  &lt;/game&gt;
        '''
        '''  &lt;!--
        '''   VB Chapter 5
        '''   --&gt;
        '''
        '''  &lt;puzzle&gt;
        '''    &lt;description&gt;
        '''      Create a function that adds a NewItem to a ListBox control and returns the ListBox
        '''    &lt;/description&gt;
        '''    &lt;code entryPoint=&quot;Example&quot;&gt;
        '''      Public Function Example (ByVal NewItem As  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Week5VisualBasic() As String
            Get
                Return ResourceManager.GetString("Week5VisualBasic", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
